### ISSUE TITLE
WXRADAR

### ISSUE THREAD

**Issue by KV4ATV** [km4ack/WXRADAR#1]
WXRADAR not working for several days and attempts with my WINLINK Telnet connection. I've done several requests and I only get an error and no response.

KV4ATV Wolfgang
Panama City, Fl

**Comment by km4ack** [comment]
I see where the system returned a radar image to you today (14NOV2023) at 11:01 CST

**Comment by km4ack** [comment]
Here's a screen shot showing the reply
![Screen Shot 2023-11-14 at 2 26 00 PM](https://github.com/km4ack/WXRADAR/assets/42844783/39d068bd-3468-4be3-b32a-e274b56bcf1b)

**Comment by KV4ATV** [comment]
It finally showed up. Quite a delay from the time I sent the request until
it showed up. Thank you for looking into it for me.

Wolfgang KV4ATV
Panama City, Fl
SKYWARN
